### PR TITLE
Add support for implicit FTPS

### PR DESCRIPTION
**Pull request by jarl-dk**
This PR adds support for implicit FTPS.

### CODE REVIEW

**Comment by shugo** [comment]
It looks fine.  Thank you!

**Comment by inkstak** [comment]
Is a release planned soon?

**Comment by hsbt** [comment]
@shugo I will release the current HEAD as `v0.2.0`

**Comment by hsbt** [comment]
done https://github.com/ruby/net-ftp/releases/tag/v0.2.0

**Comment by inkstak** [comment]
Thanks!

**Pull request merged**
