### PR TITLE
Clarify the license of net-ftp

### PR DESCRIPTION
**Pull request by shugo**
https://github.com/ruby/resolv/issues/45 realized me that LICENSE.txt contains only BSD-2-Clause license, while gemspec specifies both Ruby's and BSD-2-Clause license.  So I'd like to clarify the license.

### CODE REVIEW

**Comment by shugo** [comment]
Patch authors since 3bf64b0:

```
$ git shortlog -sn 3bf64b0..                                  
    25  Shugo Maeda
    22  Hiroshi SHIBATA
     3  Yusuke Endoh
     2  Dan Sosedoff
     2  Nobuyoshi Nakada
     2  Olle Jonsson
     2  Sorah Fukumori
     2  dependabot[bot]
     1  Benoit Daloze
     1  Gannon McGibbon
     1  Jarl Friis
     1  Jeremy Evans
     1  MSP-Greg
     1  Misaki Shioi
     1  Takashi Kokubun
     1  Vít Ondruch
     1  Yuuzou Gotou
     1  mohamed
     1  nagachika
```

@hsbt @mame @sosedoff @nobu @olleolleolle @sorah @eregon @gmcgibbon @jarl-dk @jeremyevans @MSP-Greg @shioimm @k0kubun @voxik @gotoyuzo @mohamedhafez @nagachika

**Review by hsbt — APPROVED** [review]

**Comment by shugo** [comment]
I've fixed typo in https://github.com/ruby/net-ftp/pull/32#issuecomment-2088115451:  `if you have any objection` -> `if you have no objection`.

**Comment by sorah** [comment]
I agree to apply "Ruby license or BSD-2-Clause license (dual-license)" to my commits.

**Comment by jeremyevans** [comment]
I agree to apply "Ruby license or BSD-2-Clause license (dual-license)" to my commits.

**Pull request merged**
